In [0]:
import pandas as pd
import numpy as np

In [6]:
print("NumPy version - " + np.version.version)

NumPy version - 1.18.2


In [7]:
#create 1D numpy array from a list
array_1d = np.array([1, 2, 3, 4, 5])

print (array_1d)

[1 2 3 4 5]


In [23]:
list_1 = [11,22,33,44,55]
array_1d = np.array([11,22,33,44,55])
array_1d
print(array_1d)

[11 22 33 44 55]


In [28]:
print(array_1d.dtype)

int64


In [32]:
print("Data.type - " +str(array_1d.dtype))

Data.type - int64


In [33]:
print(type(array_1d))

<class 'numpy.ndarray'>


In [34]:
#shape of array
print (array_1d.shape)

(5,)


In [0]:
arr  = range(4,12)

In [46]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
#note that range situation are solve in thst way above.

In [0]:
ar = np.arange(4,12)

In [52]:
print(ar.dtype)

int64


In [53]:
print(type(ar))

<class 'numpy.ndarray'>


In [0]:
#range with intervals
arr = np.arange(1,15,2)

In [56]:
print(arr)

[ 1  3  5  7  9 11 13]


In [57]:
list(arr)

[1, 3, 5, 7, 9, 11, 13]

In [0]:
mat = range (0,51,2)

In [60]:
list(mat)

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50]

In [0]:
r= range(0,12)

In [93]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
rr = np.arange(0,12)


In [97]:
rr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [102]:
np.arange(0,12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
#MATRICES([1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [113]:
np.arange(1,10,1),np.arange(2,12,1)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [110]:
print(np.arange(1,10,1), np.arange(2,12,1))

[1 2 3 4 5 6 7 8 9] [ 2  3  4  5  6  7  8  9 10 11]


In [111]:
list(range(1,10,1)),list(range(2,12,1))

([1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [0]:
my_mat= [[4,2,9],[32,43,68],[73,8,9]]


In [0]:
arr = np.array(my_mat)

In [120]:
arr

array([[ 4,  2,  9],
       [32, 43, 68],
       [73,  8,  9]])

In [0]:
# covert Numpy to pandas

In [0]:
pd_arr = pd.DataFrame(arr)

In [123]:
pd_arr

0   1   2
0   4   2   9
1  32  43  68
2  73   8   9

In [129]:
print(arr.dtype)

int64


In [132]:
print(arr.shape)

(3, 3)


In [133]:
print(type(arr))

<class 'numpy.ndarray'>


In [0]:
mymatrix = [list(range(1,10,1)),list(range(2,11,1))]

In [0]:
numpy_matrix = np.array(mymatrix)

In [142]:
numpy_matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [0]:

pd_matrix = pd.DataFrame(numpy_matrix)

In [144]:

pd_matrix

0  1  2  3  4  5  6  7   8
0  1  2  3  4  5  6  7  8   9
1  2  3  4  5  6  7  8  9  10

In [0]:
tt = range(1,12,1)

In [0]:
np_tt=np.array(tt)

In [157]:
np_tt

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
rr = range(1,10)

In [0]:
np_rr =np.array(rr)

In [161]:
np_rr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
print(np_rr)

[1 2 3 4 5 6 7 8 9]


In [163]:
pd.DataFrame(np_rr)

0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9

In [166]:
print(np_rr.shape)

(9,)


In [0]:
import datetime
datetime_example = datetime.datetime.now()

In [169]:
print(datetime_example)

2020-04-24 02:25:34.634182


In [0]:
array_2d = np.array([[11, 12, 13, 14, 15, 16, 17], [21, 22, 23, 24, 25, 26, 27], [31, 32, 33, 34, 35, 36, 37]])

In [322]:
array_2d

array([[11, 12, 13, 14, 15, 16, 17],
       [21, 22, 23, 24, 25, 26, 27],
       [31, 32, 33, 34, 35, 36, 37]])

In [310]:
print(array_2d)

[[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]]


In [0]:
# find slice_row = array_copy[1:2, :]

In [0]:
array_slice = array_2d[1:2, :]

In [313]:

array_slice

array([[21, 22, 23, 24, 25, 26, 27]])

In [314]:
print(array_slice)

[[21 22 23 24 25 26 27]]


In [0]:
array_slice[:,:] = 10

In [255]:
print(array_slice)

[[10 10 10 10 10 10 10]]


In [323]:

print(array_2d)


[[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]]


In [0]:
#we can do the slicing for columns as well
slice_col = array_2d[:, 1:5]

In [325]:
print(slice_col)

[[12 13 14 15]
 [22 23 24 25]
 [32 33 34 35]]


In [263]:
slice_col[slice_col>10]

array([12, 13, 14, 15, 22, 23, 24, 25, 32, 33, 34, 35])

In [286]:
slice_col[slice_col % 2 == 0]+=1
slice_col

array([[13, 13, 15, 15],
       [23, 23, 25, 25],
       [33, 33, 35, 35]])

In [326]:
print(slice_col)

[[12 13 14 15]
 [22 23 24 25]
 [32 33 34 35]]


In [328]:
#use similar logical filter to change elements in the array
#add 1 to all the odd values
slice_col[slice_col % 2 == 1]+=1
slice_col

array([[12, 14, 14, 16],
       [22, 24, 24, 26],
       [32, 34, 34, 36]])

In [0]:
#addition can be done with the plus sign or 'add' numpy function
arr_x = np.array([[10, 20, 30], [40, 50, 60]])
arr_y = np.array([[11, 21, 31], [41, 51, 61]])

In [330]:
arr_x

array([[10, 20, 30],
       [40, 50, 60]])

In [331]:
arr_y

array([[11, 21, 31],
       [41, 51, 61]])

In [0]:
#addition

In [338]:
np.add(arr_x,arr_y)

array([[ 21,  41,  61],
       [ 81, 101, 121]])

In [334]:
np.subtract(arr_x,arr_y)

array([[-1, -1, -1],
       [-1, -1, -1]])

In [335]:
np.divide(arr_x,arr_y)

array([[0.90909091, 0.95238095, 0.96774194],
       [0.97560976, 0.98039216, 0.98360656]])

In [336]:
arr_x+arr_y

array([[ 21,  41,  61],
       [ 81, 101, 121]])

In [340]:
print(np.multiply(arr_x,arr_y))

[[ 110  420  930]
 [1640 2550 3660]]


In [342]:
print(np.sqrt(arr_x))

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [344]:
print(np.exp(arr_x))


[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]


In [347]:
print(np.power(arr_x,4))

[[   10000   160000   810000]
 [ 2560000  6250000 12960000]]


In [0]:
#create random 4x6 matrix
arr = np.random.randn(4,6)

In [381]:
arr

array([[-0.58057949,  1.61337823, -0.00834761,  0.23209766, -0.7307069 ,
        -1.99439531],
       [ 0.30423086, -0.36176976, -1.49301354,  0.00414877, -1.72673944,
        -1.24733651],
       [ 1.10389066, -0.76704212, -0.87672435,  1.59949902, -0.2386696 ,
         1.85168389],
       [ 0.16365926, -1.6305275 ,  0.09221668, -0.2822606 ,  0.26342379,
         1.63501995]])

In [0]:
art = np.random.rand(4,6)

In [380]:
art

array([[0.59814171, 0.76413707, 0.78416281, 0.30880063, 0.3480673 ,
        0.42896871],
       [0.39838589, 0.35365137, 0.13753783, 0.68421757, 0.47615907,
        0.59260122],
       [0.5985396 , 0.0414405 , 0.93268459, 0.23982257, 0.25215521,
        0.17990027],
       [0.6143539 , 0.90826595, 0.5193754 , 0.3596652 , 0.86486675,
        0.92207479]])

In [382]:
np.random.randn(2)

array([0.06493406, 1.41992333])

In [383]:
print(arr.mean())

-0.12811933172380865


In [371]:
arr.mean(axis=1)

array([-0.2447589 , -0.75341327,  0.44543958,  0.04025526])

In [372]:
arr.mean(axis=0)

array([ 0.24780032, -0.28649029, -0.5714672 ,  0.38837121, -0.60817304,
        0.06124301])

In [376]:
np.median(arr)

-0.12350860547696998

In [377]:
np.sum(arr)

-3.0748639613714075

In [384]:
arr.sum()

-3.0748639613714075

In [0]:
np.savetxt('array.txt' , X = arr, delimiter = ',')

In [396]:
np.loadtxt('array.txt' , delimiter = ',')


array([[-0.58057949,  1.61337823, -0.00834761,  0.23209766, -0.7307069 ,
        -1.99439531],
       [ 0.30423086, -0.36176976, -1.49301354,  0.00414877, -1.72673944,
        -1.24733651],
       [ 1.10389066, -0.76704212, -0.87672435,  1.59949902, -0.2386696 ,
         1.85168389],
       [ 0.16365926, -1.6305275 ,  0.09221668, -0.2822606 ,  0.26342379,
         1.63501995]])

In [0]:
#YOU CAN CONYINUE WORKING ON YOUR VALUE

Pandas

Pandas is an numerical open source python library that is built on top of NumPy. Why learning Pandas is important:

Pandas allows you do fast analysis as well as data cleaning and preparation Pandas can work well with data from a wide variety of sources such as; Excel sheet, csv file, sql file or even a webpage

Documentation - https://pandas.pydata.org/pandas-docs/version/0.25.3/


In [0]:
import pandas as pd

In [0]:
ls = ['a','b','c','d']

In [0]:
Ser_1 = pd.Series(ls)

In [12]:
print(Ser_1)

0    a
1    b
2    c
3    d
dtype: object


In [0]:
import numpy as np


In [0]:
arr = np.array([10,20,30,40,50])

In [0]:
index = np.array(['sarah','john','olu','sola','bode'])

In [0]:
ser_3 = pd.Series(arr,index)

In [20]:
print(ser_3)

sarah    10
john     20
olu      30
sola     40
bode     50
dtype: int64


In [0]:
ser_4 = pd.Series(index,arr)

In [22]:
print(ser_4)

10    sarah
20     john
30      olu
40     sola
50     bode
dtype: object


In [29]:

print (ser_3[[3]])

sola    40
dtype: int64


In [26]:
print (ser_3[[0, 2, 4]])

sarah    10
olu      30
bode     50
dtype: int64


In [36]:
#Creating from a list of lists
pet_info = [['Blain', 10, 'Dog'], ['Lucy', 4 , 'Cat'], ['Cinco', 8, 'Rabbit']]
pet_info

[['Blain', 10, 'Dog'], ['Lucy', 4, 'Cat'], ['Cinco', 8, 'Rabbit']]

In [42]:
pet_df = pd.DataFrame(pet_info, columns = ['Name', 'Age', 'Type'],
                      index = ['A', 'B', 'C'])
                     
pet_df

Name  Age    Type
A  Blain   10     Dog
B   Lucy    4     Cat
C  Cinco    8  Rabbit

In [44]:
pet_df['Name']

A    Blain
B     Lucy
C    Cinco
Name: Name, dtype: object

In [48]:
print(type(pet_df))

<class 'pandas.core.frame.DataFrame'>


In [53]:
print(pet_df.dtypes)

Name    object
Age      int64
Type    object
dtype: object


In [0]:
#Create a list of lists that contain [[Month, Month #(Dec=12, etc.), Season]]
#Create a Pandas DataFrame with the columns = ['Month', 'day', 'Season']

In [0]:
season_info=[['Jan',15,'Winter',],['April',23,'Spring'],['July',19,'Summer'],['October', 3,'Fall']]

In [79]:
season_info

[['Jan', 15, 'Winter'],
 ['April', 23, 'Spring'],
 ['July', 19, 'Summer'],
 ['October', 3, 'Fall']]

In [0]:
season_df = pd.DataFrame(season_info,columns = ['Name', 'Day', 'Season'],
                      index = ['A', 'B', 'C','D'])

In [82]:
season_df

Name  Day  Season
A      Jan   15  Winter
B    April   23  Spring
C     July   19  Summer
D  October    3    Fall

In [83]:
pet_df.iloc[0]

Name    Blain
Age        10
Type      Dog
Name: A, dtype: object

In [87]:
pet_df.loc['B']

Name    Lucy
Age        4
Type     Cat
Name: B, dtype: object

In [88]:
season_df.iloc[2]

Name        July
Day           19
Season    Summer
Name: C, dtype: object

In [89]:
season_df.iloc[:2]

Name  Day  Season
A    Jan   15  Winter
B  April   23  Spring

In [94]:
season_df.loc['A':'C']

Name  Day  Season
A    Jan   15  Winter
B  April   23  Spring
C   July   19  Summer

APPLY CONCEPTS TO A DATA SET


In [0]:
from sklearn.datasets import load_iris
iris = load_iris()
data = iris.data
column_names = iris.feature_names

In [96]:
column_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [97]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [98]:
len(data)

150

In [99]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [101]:
data[2:5,:2]

array([[4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [105]:
data[2:5]

array([[4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [107]:
data[0:10:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.4, 2.9, 1.4, 0.2]])

In [0]:
df = pd.DataFrame(data, columns = column_names)

In [111]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [0]:
'''saving to google colab
'''
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
gdrive = GoogleDrive(gauth)

In [118]:
df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [119]:
df.tail(15)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [120]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         150.000000        150.000000         150.000000        150.000000
mean            5.843333          3.057333           3.758000          1.199333
std             0.828066          0.435866           1.765298          0.762238
min             4.300000          2.000000           1.000000          0.100000
25%             5.100000          2.800000           1.600000          0.300000
50%             5.800000          3.000000           4.350000          1.300000
75%             6.400000          3.300000           5.100000          1.800000
max             7.900000          4.400000           6.900000          2.500000

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [122]:
df.loc[140:]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [124]:
df.iloc[140:]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [125]:
df.mode()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.0               3.0                1.4               0.2
1                NaN               NaN                1.5               NaN

In [126]:
df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [129]:
df['sepal width (cm)'].mean()

3.057333333333334

In [130]:
df.mean(axis=0)

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [131]:
df.mean(axis=1)

0      2.550
1      2.375
2      2.350
3      2.350
4      2.550
       ...  
145    4.300
146    3.925
147    4.175
148    4.325
149    3.950
Length: 150, dtype: float64

In [132]:
df.groupby(['sepal width (cm)']).mean()

sepal length (cm)  petal length (cm)  petal width (cm)
sepal width (cm)                                                        
2.0                        5.000000           3.500000          1.000000
2.2                        6.066667           4.500000          1.333333
2.3                        5.325000           3.250000          0.975000
2.4                        5.300000           3.600000          1.033333
2.5                        5.762500           4.512500          1.550000
2.6                        6.160000           4.880000          1.420000
2.7                        5.855556           4.622222          1.555556
2.8                        6.335714           5.042857          1.707143
2.9                        6.060000           4.350000          1.320000
3.0                        6.015385           4.234615          1.403846
3.1                        6.036364           3.790909          1.245455
3.2                        5.884615           3.753846          1.261538
3.3                        6.016667           4.200000          1.566667
3.4                        5.316667           2.466667          0.716667
3.5                        5.150000           1.416667          0.300000
3.6                        5.425000           2.475000          0.750000
3.7                        5.266667           1.500000          0.266667
3.8                        6.100000           3.300000          0.900000
3.9                        5.400000           1.500000          0.400000
4.0                        5.800000           1.200000          0.200000
4.1                        5.200000           1.500000          0.100000
4.2                        5.500000           1.400000          0.200000
4.4                        5.700000           1.500000          0.400000

In [137]:
df.groupby(['petal width (cm)']).mean()

sepal length (cm)  sepal width (cm)  petal length (cm)
petal width (cm)                                                        
0.1                        4.820000          3.360000           1.380000
0.2                        4.972414          3.379310           1.444828
0.3                        4.971429          3.328571           1.428571
0.4                        5.300000          3.785714           1.571429
0.5                        5.100000          3.300000           1.700000
0.6                        5.000000          3.500000           1.600000
1.0                        5.414286          2.371429           3.628571
1.1                        5.400000          2.466667           3.566667
1.2                        5.780000          2.740000           4.240000
1.3                        5.884615          2.746154           4.176923
1.4                        6.325000          2.912500           4.637500
1.5                        6.183333          2.816667           4.658333
1.6                        6.375000          3.100000           5.025000
1.7                        5.800000          2.750000           4.750000
1.8                        6.400000          2.941667           5.333333
1.9                        6.340000          2.680000           5.320000
2.0                        6.650000          3.016667           5.550000
2.1                        6.916667          3.033333           5.783333
2.2                        6.866667          3.200000           6.033333
2.3                        6.912500          3.087500           5.700000
2.4                        6.266667          3.100000           5.433333
2.5                        6.733333          3.400000           5.933333

In [0]:
from sklearn.datasets import load_boston
boston = load_boston()
data = boston.data
column_names = boston.feature_names

In [139]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [152]:
column_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [159]:
df = pd.DataFrame(data, columns = column_names)
df

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [162]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
df.to_csv('/content/drive/My Drive/Colab Notebooks/bostondata.csv')